version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: gunicorn student_record.wsgi:application --bind 0.0.0.0:8000

  nginx:
    build: ./nginx
    ports:
      - 80:80
    image: rp:nginx
    links: -app
